#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

# Reads either a value or a list from plugin config
function plugin_read_list() {
  local prefix="BUILDKITE_PLUGIN_PIPELINE_LINTER_$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

IFS=$'\n\t'
files=()

# Evaluate all the globs and return the files that exist
for file in $(plugin_read_list FILES) ; do
  if [[ -e $file ]] ; then
    files+=("$file")
  fi
done

if [[ -z ${files:-} ]] ; then
  >&2 echo "No files found to checked"
  exit 1
fi

echo "--- :buildkite: Validating files"

VENV=openapi_validator_venv

if [ ! -f "$VENV/bin/activate" ]
then
  python3 -m venv "$VENV"
fi

# shellcheck disable=SC1090
(source "$VENV/bin/activate"
pip3 install -q --disable-pip-version-check openapi-spec-validator

for file in "${files[@]}"
do
  echo "checking $file"
  openapi-spec-validator "$file"
done)
